### ISSUE TITLE
"window is not defined" when using the new app bridge react components with next.js

### ISSUE THREAD

**Issue by dan-gamble** [Shopify/polaris-react#1803]
## Issue summary

When using any of the new(? I've only tried Loading but it also errors on Redirect) [Shopify App Bridge / React Components](https://help.shopify.com/en/api/embedded-apps/app-bridge/react-components) I get a `window is not defined` error.

## Expected behavior

They should hopefully be able to work with SSR.

## Actual behavior

Traceback:
```
ReferenceError: window is not defined
    at getRandomBytes (/Users/dangamble/Bao/Apps/party-packs/node_modules/@shopify/app-bridge/actions/uuid.js:16:45)
    at Object.generateUuid (/Users/dangamble/Bao/Apps/party-packs/node_modules/@shopify/app-bridge/actions/uuid.js:33:33)
    at Redirect.ActionSet (/Users/dangamble/Bao/Apps/party-packs/node_modules/@shopify/app-bridge/actions/helper.js:93:39)
    at new Redirect (/Users/dangamble/Bao/Apps/party-packs/node_modules/@shopify/app-bridge/actions/Navigation/Redirect/actions.js:99:23)
    at Object.create (/Users/dangamble/Bao/Apps/party-packs/node_modules/@shopify/app-bridge/actions/Navigation/Redirect/actions.js:134:12)
    at Index (webpack:///pages/index.js:6:1)
    at processChild (/Users/dangamble/Bao/Apps/party-packs/node_modules/react-dom/cjs/react-dom-server.node.development.js:2888:14)
    at resolve (/Users/dangamble/Bao/Apps/party-packs/node_modules/react-dom/cjs/react-dom-server.node.development.js:2812:5)
    at ReactDOMServerRenderer.render (/Users/dangamble/Bao/Apps/party-packs/node_modules/react-dom/cjs/react-dom-server.node.development.js:3202:22)
    at ReactDOMServerRenderer.read (/Users/dangamble/Bao/Apps/party-packs/node_modules/react-dom/cjs/react-dom-server.node.development.js:3161:29)
    at renderToString (/Users/dangamble/Bao/Apps/party-packs/node_modules/react-dom/cjs/react-dom-server.node.development.js:3646:27)
    at render (/Users/dangamble/Bao/Apps/party-packs/node_modules/next-server/dist/server/render.js:86:16)
    at renderPage (/Users/dangamble/Bao/Apps/party-packs/node_modules/next-server/dist/server/render.js:211:20)
    at Function.value (webpack:///node_modules/next/dist/pages/_document.js:109:1)
    at Object.loadGetInitialProps (/Users/dangamble/Bao/Apps/party-packs/node_modules/next-server/dist/lib/utils.js:42:35)
    at Object.renderToHTML (/Users/dangamble/Bao/Apps/party-packs/node_modules/next-server/dist/server/render.js:218:36)
```

## Steps to reproduce the problem

1. Use any part of the Shopify App Bridge(?) with next.js and SSR enabled

## Reduced test case

Very simple `index.js` template:

```javascript
import { Redirect } from "@shopify/app-bridge/actions";
import { Heading, Link, List, Page } from "@shopify/polaris";
import PropTypes from "prop-types";

const Index = ({ appBridge }) => {
  const redirect = Redirect.create(appBridge);

  return (
    <Page>
      <Heading>Party Packs 🎉</Heading>

      <List type="bullet">
        <List.Item>
          <Link
            url="/free-gift-codes"
            onClick={() => {
              redirect.dispatch(Redirect.Action.APP, "/free-gift-codes");
            }}
          >
            Free Gift Codes
          </Link>
        </List.Item>
      </List>
    </Page>
  );
};

Index.propTypes = {
  appBridge: PropTypes.object
};

export default Index;
```

## Specifications

- Are you using the React components? Y
- Polaris version number: 3.16.0
- Browser: Chrome 75
- Device: iMac
- Operating System: OSX

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash
  System:
    OS: macOS 10.14.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 8.84 GB / 40.00 GB
    Shell: 5.7.1 - /usr/local/bin/zsh
  Binaries:
    Node: 12.4.0 - ~/.nvm/versions/node/v12.4.0/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.4.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 75.0.3770.100
    Firefox: 66.0.2
    Firefox Developer Edition: 67.0
    Safari: 12.1
  npmPackages:
    @shopify/polaris: ^3.16.0 => 3.18.0
    react: ^16.8.6 => 16.8.6
    react-dom: ^16.8.6 => 16.8.6
```

**Comment by iainmcampbell** [comment]
Hi Dan! Thanks for the detailed bug report.

The App Bridge React library isn’t owned by the Polaris team, so I’m going to close this issue so it’s off their backlog. I’ve opened a corresponding issue on my team’s board, which is unfortunately not public. I’ll post updates here as we have them.

**Comment by dan-gamble** [comment]
Awesome, thank you @iainmcampbell 🤙

**Comment by oliver-austin** [comment]
Same problem here when using Redirects
