### ISSUE TITLE
[DatePicker] Error in translation for key 'Polaris.DatePicker.previousMonth'

### ISSUE THREAD

**Issue by alain-andre** [Shopify/polaris-react#2943]
## Issue summary

I'm trying to use the DatePicker following the [Shopify React tutorial](https://shopify.dev/tutorials/build-a-shopify-app-with-node-and-react/set-up-your-app) and it fails because of the following error.

``` 
Error in translation for key 'Polaris.DatePicker.previousMonth'. No replacement found for key 'showPreviousYear'. The following replacements were passed: '{"previousMonthName":""}'
```

## Expected behavior

I just want to be able to pick a date and use it to send to an external API.

## Actual behavior

Page fails on load  with following stack  trace : 

<details>
Error: Error in translation for key 'Polaris.DatePicker.previousMonth'. No replacement found for key 'showPreviousYear'. The following replacements were passed: '{"previousMonthName":""}'
    at /home/alain/Dev/mapotempo-shopify/node_modules/@shopify/polaris/index.js:587:19
    at String.replace (<anonymous>)
    at I18n.translate (/home/alain/Dev/mapotempo-shopify/node_modules/@shopify/polaris/index.js:582:21)
    at DatePicker (/home/alain/Dev/mapotempo-shopify/node_modules/@shopify/polaris/index.js:9012:30)
    at processChild (/home/alain/Dev/mapotempo-shopify/node_modules/react-dom/cjs/react-dom-server.node.development.js:3043:14)
    at resolve (/home/alain/Dev/mapotempo-shopify/node_modules/react-dom/cjs/react-dom-server.node.development.js:2960:5)
    at ReactDOMServerRenderer.render (/home/alain/Dev/mapotempo-shopify/node_modules/react-dom/cjs/react-dom-server.node.development.js:3435:22)
    at ReactDOMServerRenderer.read (/home/alain/Dev/mapotempo-shopify/node_modules/react-dom/cjs/react-dom-server.node.development.js:3373:29)
    at renderToString (/home/alain/Dev/mapotempo-shopify/node_modules/react-dom/cjs/react-dom-server.node.development.js:3988:27)
    at render (/home/alain/Dev/mapotempo-shopify/node_modules/next/dist/next-server/server/render.js:83:16)
    at Object.renderPage (/home/alain/Dev/mapotempo-shopify/node_modules/next/dist/next-server/server/render.js:419:16)
    at Function.getInitialProps (/home/alain/Dev/mapotempo-shopify/.next/server/static/development/pages/_document.js:293:19)
    at Object.loadGetInitialProps (/home/alain/Dev/mapotempo-shopify/node_modules/next/dist/next-server/lib/utils.js:59:29)
    at Object.renderToHTML (/home/alain/Dev/mapotempo-shopify/node_modules/next/dist/next-server/server/render.js:423:36)
</details>

## Steps to reproduce the problem
From the tutorial 

I'm having in `_app.js` the i18 set as it is in tutorial
```
<AppProvider i18n={translations}>
``` 

In `index.js` I changed the code as this : 

``` js
import {
  DatePicker,
  Layout,
  Page,
} from '@shopify/polaris';

class Index extends React.Component {
  state = {
    month: today.getMonth(),
    year: today.getYear(),
  };

render() {
  return (
    <Page>
      <Layout>
        <DatePicker
          month={this.month}
          year={this.year}
          onMonthChange={this.handleMonthChange()}
        />
      </Layout>
    </Page>
  )

  handleMonthChange = (obj) => {
    console.log(obj)
  }
}

export default Index;
``` 

## Specifications

- Are you using the React components? (Y/N): Y

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash
npx : 1 installé(s) en 1.694s

  System:
    OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i3-5010U CPU @ 2.10GHz
    Memory: 636.90 MB / 11.62 GB
    Container: Yes
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 10.14.0 - ~/.nvm/versions/node/v10.14.0/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.14.0/bin/npm
  Browsers:
    Chrome: 81.0.4044.113
    Firefox: 75.0
  npmPackages:
    @shopify/polaris: ^4.19.0 => 4.19.0 
    react: ^16.13.1 => 16.13.1 
    react-dom: ^16.13.1 => 16.13.1 
```

**Comment by alain-andre** [comment]
I have made this sandbox https://codesandbox.io/s/shopify-polaris-react-error-datepicker-l8xul?file=/src/index.js

**Comment by chloerice** [comment]
Hi @alain-andre 👋 in your sandbox the month and year are coming from `state` but they're being set on the `DatePicker` as instance properties. Changing `this.month` and `this.year` to `this.state.month` and `this.state.year` fixes the problem. [See my fork of your sandbox](https://codesandbox.io/s/shopify-polaris-react-error-datepicker-ugfc7).
