### ISSUE TITLE
Page component does not render

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/polaris-react#697]
# Issue summary

Lay down a Page component in an AppProvider, generates errors.

Can render a Card without a Page, but simply laying down a Page component blows chunks. Why would trying to render a <Page> blow chunks? Why a postMessage? Huh? 

## Expected behavior

React should render a Page

## Actual behavior

Nothing renders and console is full of errors... like this...

    index.js:1 Uncaught DOMException: Failed to execute 'postMessage' on 'Window': HTMLDivElement 
     object could not be cloned.
        at Object.dispatch (https://foo.test/packs/application-6f25e935f5f5ea9ae2b0.js:63178:68869)
        at Object.dispatch (https://foo.test/packs/application-6f25e935f5f5ea9ae2b0.js:63178:70807)
        at r.dispatch (https://foo.test/packs/application-6f25e935f5f5ea9ae2b0.js:65967:65888)
        at r.set (https://foo.test/packs/application-6f25e935f5f5ea9ae2b0.js:65967:65777)
        at new r (https://foo.test/packs/application-6f25e935f5f5ea9ae2b0.js:65967:64709)
        at Object.d [as create] (https://foo.test/packs/application-6f25e935f5f5ea9ae2b0.js:65967:63663)
        at Page.componentDidMount (https://foo.test/packs/application-6f25e935f5f5ea9ae2b0.js:49596:100)
        at commitLifeCycles (https://foo.test/packs/application-6f25e935f5f5ea9ae2b0.js:33593:22)
        at commitAllLifeCycles (https://foo.test/packs/application-6f25e935f5f5ea9ae2b0.js:34687:7)
        at HTMLUnknownElement.callCallback (https://foo.test/packs/application-6f25e935f5f5ea9ae2b0.js:19445:14)

Additionally, the console shows this... probably helps...

    react-dom.development.js:14113 The above error occurred in the <Page> component:
        in Page (created by WithProvider)
        in WithProvider
        in div (created by ThemeProvider)
        in ThemeProvider (created by AppProvider)
        in AppProvider

    Consider adding an error boundary to your tree to customize error handling behavior.
    Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

## Steps to reproduce the problem

1. Install Polaris with Yarn, so at latest 3.1.1
2. Run simple App in Browser.

Here is simple App... gets API key from layout rendered in Rails. A Card works.. but a Page does not.

    import React, { Component } from "react";
    import { render } from 'react-dom';
    import * as PropTypes from 'prop-types';
    import {
      AppProvider,
      Page,
    } from '@shopify/polaris';

    document.addEventListener('DOMContentLoaded', () => {
        const shopOrigin = document.querySelector('#ShopOrigin').textContent
       const apiKey = document.querySelector('#APIKey').textContent
       render(
         <AppProvider
           apiKey={apiKey}
 
         >
         <Page
           title="Jar With Lock-Lid"
          >
             <p>Page content</p>
          </Page>
        </AppProvider>,
        document.getElementById("app")
      );
   })

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.1.1
- Browser: Chrome
- Device: computer
- Operating System: MacOS Mojave

**Comment by BPScott** [comment]
@tmlayton Can you take a look at this, I'm not familiar with the AppProvider integration

**Comment by danrosenthal** [comment]
This feels related to https://github.com/Shopify/polaris-react/issues/669
