### ISSUE TITLE
Deploy script opening a PR to polaris-styleguide sometimes fails

### ISSUE THREAD

**Issue by kaelig** [Shopify/polaris-react#917]
Part of the 3.5.0 deploy of polaris-react failed (see https://shipit.shopify.io/shopify/polaris-react/production/deploys/708703):

```
Switched to a new branch 'update-polaris-v3.5.0'
warning Resolution field "@types/zen-observable@0.5.4" is incompatible with requested version "@types/zen-observable@^0.8.0"
error Couldn't find any versions for "@shopify/polaris" that matches "3.5.0"
child_process.js:650
    throw err;
    ^
Error: Command failed: yarn upgrade @shopify/polaris@3.5.0 --no-progress --ignore-engines
warning Resolution field "@types/zen-observable@0.5.4" is incompatible with requested version "@types/zen-observable@^0.8.0"
error Couldn't find any versions for "@shopify/polaris" that matches "3.5.0"
    at checkExecSyncError (child_process.js:607:13)
    at execSync (child_process.js:647:13)
    at Object.<anonymous> (/app/data/stacks/shopify/polaris-react/production/deploys/708703/scripts/open-styleguide-pr.js:67:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @shopify/polaris@3.5.0 open-styleguide-pr: `node ./scripts/open-styleguide-pr`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @shopify/polaris@3.5.0 open-styleguide-pr script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/borg/.npm/_logs/2019-01-16T21_27_12_659Z-debug.log
ERROR: "open-styleguide-pr" exited with 1.
```

I believe this is caused by a lag in the npm registry, and the package couldn’t be found at the time the `yarn upgrade @shopify/polaris@3.5.0` command ran.

A possible fix could be to wait ~30s before running the `open-styleguide-pr` script, leaving some time for the npm registry to propagate the new version.

Another way suggested by @amrocha  would be to retry `yarn upgrade` a few times, or try to fetch the version from the npm API until it returns a valid thing, and only then run `yarn upgrade`.

**Comment by kaelig** [comment]
Closing as this is such a rare occasion and not critical – so investing in this may not be very impactful.
